# -*- coding: utf-8 -*-
"""analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wywqFbTMxQZgdmlPZ4H8LyItWr6iWgtK
"""

# ============================================================
# analytics.py
# Ce fichier contient les analyses statistiques du projet
# ============================================================

import pandas as pd
from scipy.stats import chisquare


def genre_distribution(watch_history_df):
    """
    Cette fonction calcule la distribution des genres regardes.
    """

    return watch_history_df["genre"].value_counts()


def average_rating_by_genre(watch_history_df):
    """
    Cette fonction calcule la note moyenne par genre.
    """

    return (
        watch_history_df.groupby("genre")["rating"]
        .mean()
        .sort_values(ascending=False)
    )


def top_movies(watch_history_df, top_n=10):
    """
    Cette fonction retourne les films les plus regardes.
    """

    return watch_history_df["title"].value_counts().head(top_n)


def most_active_users(watch_history_df, top_n=10):
    """
    Cette fonction retourne les utilisateurs les plus actifs.
    """

    return watch_history_df["user_name"].value_counts().head(top_n)


def average_watch_time_by_genre(watch_history_df):
    """
    Cette fonction calcule le temps moyen de visionnage par genre.
    """

    return (
        watch_history_df.groupby("genre")["watch_time"]
        .mean()
        .sort_values(ascending=False)
    )


def chi_square_genre_test(watch_history_df):
    """
    Cette fonction applique le test Chi-square sur les genres.
    Objectif : verifier si les genres sont regardes de facon equilibree.
    """

    genre_counts = watch_history_df["genre"].value_counts()

    chi_stat, p_value = chisquare(genre_counts.values)

    return chi_stat, p_value