# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyDgsAYI2sNguUMoSGWBnPbycdnESnsA
"""

# ============================================================
# dashboard.py
# Ce fichier contient les visualisations du dashboard admin
# ============================================================

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


def plot_genre_distribution(watch_history_df):
    """
    Cette fonction affiche la distribution des genres regardes.
    """

    genre_counts = watch_history_df["genre"].value_counts()

    plt.figure(figsize=(8, 5))
    plt.bar(genre_counts.index, genre_counts.values)
    plt.title("Distribution des genres regardes")
    plt.xlabel("Genre")
    plt.ylabel("Nombre de visionnages")
    plt.xticks(rotation=45)
    plt.grid(axis="y")
    plt.tight_layout()
    plt.show()


def plot_average_rating_by_genre(watch_history_df):
    """
    Cette fonction affiche la note moyenne par genre.
    """

    avg_rating = (
        watch_history_df.groupby("genre")["rating"]
        .mean()
        .sort_values(ascending=False)
    )

    plt.figure(figsize=(8, 5))
    plt.bar(avg_rating.index, avg_rating.values)
    plt.title("Note moyenne par genre")
    plt.xlabel("Genre")
    plt.ylabel("Note moyenne")
    plt.xticks(rotation=45)
    plt.grid(axis="y")
    plt.tight_layout()
    plt.show()


def plot_top_movies(watch_history_df):
    """
    Cette fonction affiche les films les plus regardes.
    """

    top_movies = watch_history_df["title"].value_counts().head(10)

    plt.figure(figsize=(10, 5))
    plt.bar(top_movies.index, top_movies.values)
    plt.title("Top 10 des films les plus regardes")
    plt.xlabel("Film")
    plt.ylabel("Nombre de visionnages")
    plt.xticks(rotation=45, ha="right")
    plt.grid(axis="y")
    plt.tight_layout()
    plt.show()


def plot_rating_trend(watch_history_df):
    """
    Cette fonction affiche l'evolution moyenne des notes dans le temps.
    """

    rating_trend = (
        watch_history_df.groupby("watch_date")["rating"]
        .mean()
        .reset_index()
        .sort_values(by="watch_date")
    )

    plt.figure(figsize=(10, 5))
    plt.plot(rating_trend["watch_date"], rating_trend["rating"], marker="o")
    plt.title("Evolution des notes moyennes dans le temps")
    plt.xlabel("Date")
    plt.ylabel("Note moyenne")
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    plt.show()


def plot_user_genre_heatmap(watch_history_df):
    """
    Cette fonction affiche une heatmap utilisateur-genre.
    """

    heatmap_data = pd.crosstab(
        watch_history_df["user_name"],
        watch_history_df["genre"]
    )

    plt.figure(figsize=(10, 6))
    sns.heatmap(heatmap_data, annot=True, cmap="Blues")
    plt.title("Heatmap utilisateurs / genres")
    plt.xlabel("Genre")
    plt.ylabel("Utilisateur")
    plt.tight_layout()
    plt.show()