# -*- coding: utf-8 -*-
"""data_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sQnC-ilEvRRWjuN2TjQwpM07kDNSKDT
"""

# ============================================================
# data_generator.py
# Ce fichier genere les donnees synthetiques du projet
# Il peut aussi ajouter volontairement des erreurs dans les donnees
# ============================================================

import numpy as np
import pandas as pd
from faker import Faker


# Initialiser Faker pour generer de faux noms
fake = Faker()

# Fixer la seed pour avoir les memes resultats a chaque execution
np.random.seed(42)
Faker.seed(42)


def generate_movies():
    """
    Cette fonction cree le catalogue des films disponibles.
    Dans une vraie plateforme, ces films viendraient d'une base de donnees.
    """

    movies_data = [
        {"movie_id": 1, "title": "Inception", "genre": "sci-fi", "director": "Christopher Nolan", "year": 2010, "popularity": 95},
        {"movie_id": 2, "title": "Interstellar", "genre": "sci-fi", "director": "Christopher Nolan", "year": 2014, "popularity": 97},
        {"movie_id": 3, "title": "The Matrix", "genre": "sci-fi", "director": "Wachowski Sisters", "year": 1999, "popularity": 92},
        {"movie_id": 4, "title": "John Wick", "genre": "action", "director": "Chad Stahelski", "year": 2014, "popularity": 90},
        {"movie_id": 5, "title": "Black Panther", "genre": "action", "director": "Ryan Coogler", "year": 2018, "popularity": 89},
        {"movie_id": 6, "title": "Gladiator", "genre": "action", "director": "Ridley Scott", "year": 2000, "popularity": 88},
        {"movie_id": 7, "title": "Titanic", "genre": "romance", "director": "James Cameron", "year": 1997, "popularity": 96},
        {"movie_id": 8, "title": "The Notebook", "genre": "romance", "director": "Nick Cassavetes", "year": 2004, "popularity": 85},
        {"movie_id": 9, "title": "La La Land", "genre": "romance", "director": "Damien Chazelle", "year": 2016, "popularity": 84},
        {"movie_id": 10, "title": "The Godfather", "genre": "crime", "director": "Francis Ford Coppola", "year": 1972, "popularity": 98},
        {"movie_id": 11, "title": "Joker", "genre": "crime", "director": "Todd Phillips", "year": 2019, "popularity": 87},
        {"movie_id": 12, "title": "Prisoners", "genre": "thriller", "director": "Denis Villeneuve", "year": 2013, "popularity": 82},
        {"movie_id": 13, "title": "Get Out", "genre": "thriller", "director": "Jordan Peele", "year": 2017, "popularity": 86},
        {"movie_id": 14, "title": "The Hangover", "genre": "comedy", "director": "Todd Phillips", "year": 2009, "popularity": 80},
        {"movie_id": 15, "title": "Home Alone", "genre": "comedy", "director": "Chris Columbus", "year": 1990, "popularity": 83},
        {"movie_id": 16, "title": "Avengers Endgame", "genre": "action", "director": "Russo Brothers", "year": 2019, "popularity": 99},
        {"movie_id": 17, "title": "Doctor Strange", "genre": "fantasy", "director": "Scott Derrickson", "year": 2016, "popularity": 85},
        {"movie_id": 18, "title": "Harry Potter", "genre": "fantasy", "director": "Chris Columbus", "year": 2001, "popularity": 94},
        {"movie_id": 19, "title": "The Conjuring", "genre": "horror", "director": "James Wan", "year": 2013, "popularity": 81},
        {"movie_id": 20, "title": "A Quiet Place", "genre": "horror", "director": "John Krasinski", "year": 2018, "popularity": 79}
    ]

    movies_df = pd.DataFrame(movies_data)

    return movies_df


def generate_users(number_of_users=20):
    """
    Cette fonction genere des utilisateurs avec Faker.
    Chaque utilisateur a un nom, un age et des genres preferes.
    """

    genres = ["sci-fi", "action", "romance", "crime", "thriller", "comedy", "fantasy", "horror"]

    users = []

    for user_id in range(1, number_of_users + 1):

        # Generer un nom aleatoire
        name = fake.name()

        # Generer un age aleatoire
        age = np.random.randint(18, 45)

        # Choisir 3 genres preferes
        preferences = list(np.random.choice(genres, size=3, replace=False))

        users.append({
            "user_id": user_id,
            "name": name,
            "age": age,
            "preferences": preferences
        })

    users_df = pd.DataFrame(users)

    return users_df


def generate_watch_history(users_df, movies_df, make_dirty=False):
    """
    Cette fonction genere l'historique de visionnage.
    Si make_dirty=True, elle ajoute volontairement des erreurs dans les donnees.
    """

    watch_history = []

    # Generer une periode de dates
    dates = pd.date_range(start="2026-01-01", periods=60, freq="D")

    for _, user in users_df.iterrows():

        # Recuperer les preferences de l'utilisateur
        user_preferences = user["preferences"]

        # Chaque utilisateur regarde entre 6 et 12 films
        number_of_movies_watched = np.random.randint(6, 13)

        # Choisir les films regardes
        watched_movies = movies_df.sample(number_of_movies_watched, replace=False)

        for _, movie in watched_movies.iterrows():

            # Si le genre correspond aux preferences, la note est plus elevee
            if movie["genre"] in user_preferences:
                rating = np.random.randint(4, 6)
            else:
                rating = np.random.randint(1, 5)

            # Temps de visionnage en minutes
            watch_time = np.random.randint(30, 180)

            # Date aleatoire de visionnage
            watch_date = np.random.choice(dates)

            watch_history.append({
                "user_id": user["user_id"],
                "user_name": user["name"],
                "age": user["age"],
                "movie_id": movie["movie_id"],
                "title": movie["title"],
                "genre": movie["genre"],
                "director": movie["director"],
                "rating": rating,
                "watch_time": watch_time,
                "watch_date": watch_date
            })

    watch_history_df = pd.DataFrame(watch_history)

    # Ajouter volontairement des erreurs si demande
    if make_dirty:
        watch_history_df = add_data_quality_issues(watch_history_df)

    return watch_history_df


def add_data_quality_issues(df):
    """
    Cette fonction ajoute volontairement des problemes de qualite dans les donnees.
    Objectif : permettre d'appliquer les methodes de preprocessing apprises.
    """

    dirty_df = df.copy()

    number_of_rows = len(dirty_df)

    # --------------------------------------------------------
    # 1. Ajouter des valeurs manquantes dans rating
    # --------------------------------------------------------

    missing_rating_indices = np.random.choice(
        dirty_df.index,
        size=int(number_of_rows * 0.05),
        replace=False
    )

    dirty_df.loc[missing_rating_indices, "rating"] = np.nan

    # --------------------------------------------------------
    # 2. Ajouter des valeurs manquantes dans watch_time
    # --------------------------------------------------------

    missing_watch_time_indices = np.random.choice(
        dirty_df.index,
        size=int(number_of_rows * 0.05),
        replace=False
    )

    dirty_df.loc[missing_watch_time_indices, "watch_time"] = np.nan

    # --------------------------------------------------------
    # 3. Ajouter des genres manquants
    # --------------------------------------------------------

    missing_genre_indices = np.random.choice(
        dirty_df.index,
        size=int(number_of_rows * 0.03),
        replace=False
    )

    dirty_df.loc[missing_genre_indices, "genre"] = np.nan

    # --------------------------------------------------------
    # 4. Ajouter des dates manquantes
    # --------------------------------------------------------

    missing_date_indices = np.random.choice(
        dirty_df.index,
        size=int(number_of_rows * 0.03),
        replace=False
    )

    dirty_df.loc[missing_date_indices, "watch_date"] = pd.NaT

    # --------------------------------------------------------
    # 5. Ajouter des notes invalides
    # Normalement une note doit etre entre 1 et 5
    # --------------------------------------------------------

    invalid_rating_indices = np.random.choice(
        dirty_df.index,
        size=int(number_of_rows * 0.03),
        replace=False
    )

    invalid_ratings = np.random.choice([0, -1, 6, 10], size=len(invalid_rating_indices))

    dirty_df.loc[invalid_rating_indices, "rating"] = invalid_ratings

    # --------------------------------------------------------
    # 6. Ajouter des temps de visionnage invalides
    # Normalement watch_time doit etre positif
    # --------------------------------------------------------

    invalid_watch_time_indices = np.random.choice(
        dirty_df.index,
        size=int(number_of_rows * 0.03),
        replace=False
    )

    invalid_watch_times = np.random.choice([-10, -30, 0, 500], size=len(invalid_watch_time_indices))

    dirty_df.loc[invalid_watch_time_indices, "watch_time"] = invalid_watch_times

    # --------------------------------------------------------
    # 7. Ajouter des doublons
    # --------------------------------------------------------

    duplicate_rows = dirty_df.sample(
        n=int(number_of_rows * 0.05),
        replace=False
    )

    dirty_df = pd.concat([dirty_df, duplicate_rows], ignore_index=True)

    return dirty_df