# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xFszSzoledHKSu5UEp4cMIJyqCKo2RG
"""

# ============================================================
# main.py
# Ce fichier lance tout le projet CineMatch AI
# ============================================================

from data_generator import generate_movies, generate_users, generate_watch_history
from preprocessing import check_data, clean_watch_history, create_user_movie_matrix
from recommender import MovieRecommender
from analytics import (
    genre_distribution,
    average_rating_by_genre,
    top_movies,
    most_active_users,
    average_watch_time_by_genre,
    chi_square_genre_test
)
from dashboard import (
    plot_genre_distribution,
    plot_average_rating_by_genre,
    plot_top_movies,
    plot_rating_trend,
    plot_user_genre_heatmap
)


# ============================================================
# 1. GENERATE DATA
# ============================================================

# Generer le catalogue de films
movies_df = generate_movies()

# Generer les utilisateurs avec Faker
users_df = generate_users(number_of_users=20)

# Generer l'historique de visionnage
watch_history_df = generate_watch_history(users_df, movies_df, make_dirty=True)


# ============================================================
# 2. CHECK AND CLEAN DATA
# ============================================================

# Verifier les donnees des films
check_data(movies_df, "Movies dataset")

# Verifier les donnees utilisateurs
check_data(users_df, "Users dataset")

# Verifier l'historique avant nettoyage
check_data(watch_history_df, "Watch history before cleaning")

# Nettoyer l'historique
watch_history_df = clean_watch_history(watch_history_df)

# Verifier l'historique apres nettoyage
check_data(watch_history_df, "Watch history after cleaning")


# ============================================================
# 3. CREATE MATRIX
# ============================================================

# Creer la matrice utilisateur-film
user_movie_matrix = create_user_movie_matrix(watch_history_df)


# ============================================================
# 4. CREATE RECOMMENDER ENGINE
# ============================================================

# Creer le moteur de recommandation
recommender = MovieRecommender(
    movies_df=movies_df,
    watch_history_df=watch_history_df,
    user_movie_matrix=user_movie_matrix
)


# ============================================================
# 5. USER RECOMMENDATION DEMO
# ============================================================

print("\n================ USERS ================")
print(users_df[["user_id", "name", "age", "preferences"]])

# Choisir un utilisateur pour la demonstration
target_user = users_df.iloc[0]["name"]

print(f"\nUtilisateur cible : {target_user}")

print("\nFilms deja regardes :")
print(recommender.get_user_watched_movies(target_user))

print("\nGenres favoris :")
print(recommender.get_user_favorite_genres(target_user))

print("\nUtilisateurs similaires :")
print(recommender.find_similar_users(target_user, top_n=3))

print("\nRecommandations finales :")
print(recommender.hybrid_recommendation(target_user, top_n=5))


# ============================================================
# 6. ANALYTICS
# ============================================================

print("\n================ ANALYTICS ================")

print("\nDistribution des genres :")
print(genre_distribution(watch_history_df))

print("\nNote moyenne par genre :")
print(average_rating_by_genre(watch_history_df))

print("\nTop films :")
print(top_movies(watch_history_df))

print("\nUtilisateurs les plus actifs :")
print(most_active_users(watch_history_df))

print("\nTemps moyen de visionnage par genre :")
print(average_watch_time_by_genre(watch_history_df))


# ============================================================
# 7. SCIPY ANALYSIS
# ============================================================

print("\n================ SCIPY ANALYSIS ================")

chi_stat, p_value = chi_square_genre_test(watch_history_df)

print("Chi-square statistic:", chi_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Conclusion: Les genres ne sont pas regardes de facon equilibree.")
else:
    print("Conclusion: Les genres sont regardes de facon assez equilibree.")


# ============================================================
# 8. DASHBOARD
# ============================================================

print("\n================ DASHBOARD ================")

plot_genre_distribution(watch_history_df)
plot_average_rating_by_genre(watch_history_df)
plot_top_movies(watch_history_df)
plot_rating_trend(watch_history_df)
plot_user_genre_heatmap(watch_history_df)


# ============================================================
# 9. FINAL REPORT
# ============================================================

print("\n================ FINAL REPORT ================")

print("""
CineMatch AI is an AI-powered movie recommendation system.

Since we do not have real users, we generated synthetic user data using Faker.
The system creates user profiles, movie data, and viewing history.

The recommendation engine uses:
- user favorite genres
- movie ratings
- user viewing history
- similar users
- movie popularity

The admin dashboard shows:
- genre distribution
- average rating by genre
- top watched movies
- rating trend over time
- user-genre heatmap

SciPy was used to apply a Chi-square test on genre distribution.

This project simulates how a platform like Netflix can recommend movies and analyze user behavior.
""")