# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mALfojjy8423rQ7L8MZ6VflAcv-6BP7
"""

# ============================================================
# preprocessing.py
# Ce fichier nettoie et prepare les donnees du projet
# ============================================================

import pandas as pd
import numpy as np


def check_data(df, name="Dataset"):
    """
    Cette fonction affiche les informations importantes d'un dataset.
    Elle gere aussi les colonnes qui contiennent des listes.
    """

    print(f"\n================ {name} CHECK ================")

    print("\nShape:")
    print(df.shape)

    print("\nMissing values:")
    print(df.isnull().sum())

    print("\nDuplicate rows:")

    try:
        print(df.duplicated().sum())
    except TypeError:
        # Certaines colonnes peuvent contenir des listes
        # On transforme temporairement les listes en texte
        temp_df = df.copy()

        for column in temp_df.columns:
            temp_df[column] = temp_df[column].apply(
                lambda value: str(value) if isinstance(value, list) else value
            )

        print(temp_df.duplicated().sum())

    print("\nData types:")
    print(df.dtypes)


def clean_watch_history(watch_history_df):
    """
    Cette fonction nettoie l'historique de visionnage.
    Elle corrige les valeurs manquantes, les doublons et les valeurs invalides.
    """

    clean_df = watch_history_df.copy()

    # --------------------------------------------------------
    # 1. Supprimer les doublons
    # --------------------------------------------------------

    clean_df = clean_df.drop_duplicates()

    # --------------------------------------------------------
    # 2. Convertir rating en numerique
    # --------------------------------------------------------

    clean_df["rating"] = pd.to_numeric(clean_df["rating"], errors="coerce")

    # --------------------------------------------------------
    # 3. Corriger les notes invalides
    # Une note doit etre comprise entre 1 et 5
    # Les valeurs hors limites deviennent NaN
    # --------------------------------------------------------

    clean_df.loc[
        (clean_df["rating"] < 1) | (clean_df["rating"] > 5),
        "rating"
    ] = np.nan

    # --------------------------------------------------------
    # 4. Remplacer les notes manquantes par la mediane
    # --------------------------------------------------------

    rating_median = clean_df["rating"].median()

    clean_df["rating"] = clean_df["rating"].fillna(rating_median)

    # --------------------------------------------------------
    # 5. Convertir watch_time en numerique
    # --------------------------------------------------------

    clean_df["watch_time"] = pd.to_numeric(clean_df["watch_time"], errors="coerce")

    # --------------------------------------------------------
    # 6. Corriger les temps de visionnage invalides
    # Un temps doit etre positif et raisonnable
    # Ici, on considere qu'un film ne depasse pas 240 minutes
    # --------------------------------------------------------

    clean_df.loc[
        (clean_df["watch_time"] <= 0) | (clean_df["watch_time"] > 240),
        "watch_time"
    ] = np.nan

    # --------------------------------------------------------
    # 7. Remplacer les temps manquants par la mediane
    # --------------------------------------------------------

    watch_time_median = clean_df["watch_time"].median()

    clean_df["watch_time"] = clean_df["watch_time"].fillna(watch_time_median)

    # --------------------------------------------------------
    # 8. Remplacer les genres manquants
    # --------------------------------------------------------

    clean_df["genre"] = clean_df["genre"].fillna("unknown")

    # --------------------------------------------------------
    # 9. Remplacer les realisateurs manquants
    # --------------------------------------------------------

    clean_df["director"] = clean_df["director"].fillna("unknown")

    # --------------------------------------------------------
    # 10. Convertir watch_date en datetime
    # --------------------------------------------------------

    clean_df["watch_date"] = pd.to_datetime(clean_df["watch_date"], errors="coerce")

    # --------------------------------------------------------
    # 11. Remplacer les dates manquantes par la date la plus frequente
    # --------------------------------------------------------

    if clean_df["watch_date"].isnull().sum() > 0:
        most_common_date = clean_df["watch_date"].mode()[0]
        clean_df["watch_date"] = clean_df["watch_date"].fillna(most_common_date)

    # --------------------------------------------------------
    # 12. Reinitialiser les index
    # --------------------------------------------------------

    clean_df = clean_df.reset_index(drop=True)

    return clean_df


def create_user_movie_matrix(watch_history_df):
    """
    Cette fonction cree une matrice utilisateur-film.
    Les lignes sont les utilisateurs.
    Les colonnes sont les films.
    Les valeurs sont les notes.
    """

    user_movie_matrix = watch_history_df.pivot_table(
        index="user_name",
        columns="title",
        values="rating",
        aggfunc="mean",
        fill_value=0
    )

    return user_movie_matrix


def create_user_genre_matrix(watch_history_df):
    """
    Cette fonction cree une matrice utilisateur-genre.
    Les lignes sont les utilisateurs.
    Les colonnes sont les genres.
    Les valeurs sont les notes moyennes.
    """

    user_genre_matrix = watch_history_df.pivot_table(
        index="user_name",
        columns="genre",
        values="rating",
        aggfunc="mean",
        fill_value=0
    )

    return user_genre_matrix


def data_quality_summary(df):
    """
    Cette fonction retourne un resume de la qualite des donnees.
    """

    summary = pd.DataFrame({
        "column": df.columns,
        "missing_values": df.isnull().sum().values,
        "missing_percentage": (df.isnull().sum().values / len(df)) * 100,
        "data_type": df.dtypes.astype(str).values
    })

    return summary


def compare_before_after_cleaning(raw_df, clean_df):
    """
    Cette fonction compare les donnees avant et apres nettoyage.
    """

    comparison = {
        "raw_rows": len(raw_df),
        "clean_rows": len(clean_df),
        "raw_missing_values": raw_df.isnull().sum().sum(),
        "clean_missing_values": clean_df.isnull().sum().sum(),
        "raw_duplicates": raw_df.duplicated().sum(),
        "clean_duplicates": clean_df.duplicated().sum()
    }

    return comparison