# -*- coding: utf-8 -*-
"""recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiE__zUjojwKkk0c7cMcdUnECb6HE-Sy
"""

# ============================================================
# recommender.py
# Ce fichier contient le moteur de recommandation
# ============================================================

import pandas as pd
from scipy.stats import pearsonr
from scipy.spatial.distance import cosine


class MovieRecommender:
    """
    Cette classe represente le moteur de recommandation.
    Elle recommande des films selon les preferences, l'historique et les utilisateurs similaires.
    """

    def __init__(self, movies_df, watch_history_df, user_movie_matrix):
        self.movies_df = movies_df
        self.watch_history_df = watch_history_df
        self.user_movie_matrix = user_movie_matrix

    def get_user_watched_movies(self, user_name):
        """
        Cette methode retourne les films deja regardes par un utilisateur.
        """

        user_history = self.watch_history_df[
            self.watch_history_df["user_name"] == user_name
        ]

        watched_movies = user_history["title"].unique().tolist()

        return watched_movies

    def get_user_favorite_genres(self, user_name):
        """
        Cette methode retourne les genres les mieux notes par un utilisateur.
        """

        user_history = self.watch_history_df[
            self.watch_history_df["user_name"] == user_name
        ]

        if user_history.empty:
            return []

        favorite_genres = (
            user_history.groupby("genre")["rating"]
            .mean()
            .sort_values(ascending=False)
            .head(3)
            .index
            .tolist()
        )

        return favorite_genres

    def recommend_by_genre(self, user_name, top_n=5):
        """
        Cette methode recommande des films selon les genres preferes de l'utilisateur.
        """

        watched_movies = self.get_user_watched_movies(user_name)
        favorite_genres = self.get_user_favorite_genres(user_name)

        # Selectionner les films qui correspondent aux genres preferes
        recommendations = self.movies_df[
            self.movies_df["genre"].isin(favorite_genres)
        ]

        # Exclure les films deja regardes
        recommendations = recommendations[
            ~recommendations["title"].isin(watched_movies)
        ]

        # Classer par popularite
        recommendations = recommendations.sort_values(
            by="popularity",
            ascending=False
        ).head(top_n)

        return recommendations

    def calculate_similarity(self, user1, user2):
        """
        Cette methode calcule la similarite entre deux utilisateurs.
        Elle utilise la distance cosinus.
        """

        if user1 not in self.user_movie_matrix.index:
            return 0

        if user2 not in self.user_movie_matrix.index:
            return 0

        vector1 = self.user_movie_matrix.loc[user1].values
        vector2 = self.user_movie_matrix.loc[user2].values

        # Si les deux vecteurs sont vides, retourner 0
        if vector1.sum() == 0 or vector2.sum() == 0:
            return 0

        # La distance cosinus est transformee en similarite
        similarity = 1 - cosine(vector1, vector2)

        return similarity

    def find_similar_users(self, user_name, top_n=3):
        """
        Cette methode trouve les utilisateurs les plus similaires.
        """

        similarities = []

        for other_user in self.user_movie_matrix.index:

            if other_user != user_name:
                similarity = self.calculate_similarity(user_name, other_user)

                similarities.append({
                    "user_name": other_user,
                    "similarity": similarity
                })

        similarity_df = pd.DataFrame(similarities)

        similarity_df = similarity_df.sort_values(
            by="similarity",
            ascending=False
        ).head(top_n)

        return similarity_df

    def recommend_by_similar_users(self, user_name, top_n=5):
        """
        Cette methode recommande les films aimes par des utilisateurs similaires.
        """

        watched_movies = self.get_user_watched_movies(user_name)

        similar_users_df = self.find_similar_users(user_name, top_n=3)

        similar_user_names = similar_users_df["user_name"].tolist()

        similar_users_history = self.watch_history_df[
            self.watch_history_df["user_name"].isin(similar_user_names)
        ]

        # Garder les films bien notes par les utilisateurs similaires
        recommendations = similar_users_history[
            similar_users_history["rating"] >= 4
        ]

        # Exclure les films deja regardes
        recommendations = recommendations[
            ~recommendations["title"].isin(watched_movies)
        ]

        # Calculer la note moyenne des films recommandes
        recommendations = (
            recommendations.groupby(["title", "genre", "director"])["rating"]
            .mean()
            .reset_index()
            .sort_values(by="rating", ascending=False)
            .head(top_n)
        )

        return recommendations

    def hybrid_recommendation(self, user_name, top_n=5):
        """
        Cette methode combine les recommandations par genre et par utilisateurs similaires.
        """

        genre_recs = self.recommend_by_genre(user_name, top_n=top_n)
        similar_recs = self.recommend_by_similar_users(user_name, top_n=top_n)

        final_recommendations = []

        # Ajouter les recommandations par genre avec un score
        for _, movie in genre_recs.iterrows():
            final_recommendations.append({
                "title": movie["title"],
                "genre": movie["genre"],
                "director": movie["director"],
                "score": movie["popularity"],
                "source": "favorite_genre"
            })

        # Ajouter les recommandations par utilisateurs similaires avec un score
        for _, movie in similar_recs.iterrows():
            final_recommendations.append({
                "title": movie["title"],
                "genre": movie["genre"],
                "director": movie["director"],
                "score": movie["rating"] * 20,
                "source": "similar_users"
            })

        final_df = pd.DataFrame(final_recommendations)

        if final_df.empty:
            return final_df

        # Supprimer les doublons et garder le meilleur score
        final_df = (
            final_df.groupby(["title", "genre", "director"])
            .agg({"score": "max", "source": "first"})
            .reset_index()
            .sort_values(by="score", ascending=False)
            .head(top_n)
        )

        return final_df

    def pearson_similarity(self, user1, user2):
        """
        Cette methode calcule la correlation de Pearson entre deux utilisateurs.
        """

        if user1 not in self.user_movie_matrix.index:
            return None

        if user2 not in self.user_movie_matrix.index:
            return None

        vector1 = self.user_movie_matrix.loc[user1].values
        vector2 = self.user_movie_matrix.loc[user2].values

        # Pearson a besoin de variation dans les deux vecteurs
        if len(set(vector1)) == 1 or len(set(vector2)) == 1:
            return None

        corr, p_value = pearsonr(vector1, vector2)

        return corr, p_value