# -*- coding: utf-8 -*-
"""web_admin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5ol3zXRRQ8FGVy6QISrPI2xp4QkvQXL
"""

# ============================================================
# web_admin.py
# CineMatch AI - Admin Dashboard
# Dashboard web admin Streamlit
# ============================================================

# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go

import time
import random

from data_generator import generate_movies, generate_users, generate_watch_history

from preprocessing import (
    clean_watch_history,
    create_user_movie_matrix,
    data_quality_summary,
    compare_before_after_cleaning
)

from recommender import MovieRecommender

from analytics import (
    genre_distribution,
    average_rating_by_genre,
    top_movies,
    most_active_users,
    average_watch_time_by_genre,
    chi_square_genre_test
)


# ============================================================
# 2. PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="CineMatch AI Admin Dashboard",
    page_icon="🎬",
    layout="wide"
)


# ============================================================
# 3. CUSTOM CSS
# ============================================================

st.markdown(
    """
    <style>

    .stApp {
        background: linear-gradient(135deg, #050505 0%, #111827 45%, #2B0000 100%);
        color: #F9FAFB;
    }

    section[data-testid="stSidebar"] {
        background: linear-gradient(180deg, #000000 0%, #111827 60%, #1A0000 100%);
        border-right: 1px solid #E50914;
    }

    h1 {
        color: #FFFFFF;
        font-size: 42px !important;
        font-weight: 800 !important;
    }

    h2, h3 {
        color: #FF2E2E;
        font-weight: 700 !important;
    }

    p, div, span {
        color: #F3F4F6;
    }

    div[data-testid="stMetric"] {
        background: linear-gradient(135deg, #1F2937 0%, #111827 50%, #3B0000 100%);
        padding: 20px;
        border-radius: 18px;
        border: 1px solid rgba(229, 9, 20, 0.5);
        box-shadow: 0px 0px 18px rgba(229, 9, 20, 0.18);
    }

    div[data-testid="stMetricLabel"] {
        color: #D1D5DB;
        font-weight: 600;
    }

    div[data-testid="stMetricValue"] {
        color: #FFFFFF;
        font-size: 28px;
        font-weight: 800;
    }

    div[data-testid="stDataFrame"] {
        background-color: #111827;
        border-radius: 10px;
    }

    .hero-box {
        background: linear-gradient(120deg, #E50914 0%, #7F1D1D 45%, #111827 100%);
        padding: 30px;
        border-radius: 22px;
        margin-bottom: 25px;
        box-shadow: 0px 0px 25px rgba(229, 9, 20, 0.35);
    }

    .hero-title {
        font-size: 44px;
        font-weight: 900;
        color: white;
        margin-bottom: 5px;
    }

    .hero-subtitle {
        font-size: 18px;
        color: #F3F4F6;
    }

    .section-box {
        background: rgba(17, 24, 39, 0.85);
        padding: 20px;
        border-radius: 18px;
        border: 1px solid rgba(255, 255, 255, 0.08);
        margin-bottom: 20px;
    }

    .stButton > button {
        background: linear-gradient(90deg, #E50914 0%, #FF4D4D 100%);
        color: white;
        border-radius: 12px;
        border: none;
        padding: 10px 22px;
        font-weight: 700;
    }

    .stButton > button:hover {
        background: linear-gradient(90deg, #B20710 0%, #E50914 100%);
        color: white;
    }

    .small-text {
        color: #D1D5DB;
        font-size: 15px;
    }

    </style>
    """,
    unsafe_allow_html=True
)


# ============================================================
# 4. LOAD DATA
# ============================================================

@st.cache_data
def load_data():
    """
    Cette fonction genere les donnees brutes, nettoie les donnees,
    cree la matrice utilisateur-film et initialise le moteur de recommandation.
    """

    movies_df = generate_movies()

    users_df = generate_users(number_of_users=30)

    raw_watch_history_df = generate_watch_history(
        users_df,
        movies_df,
        make_dirty=True
    )

    clean_watch_history_df = clean_watch_history(raw_watch_history_df)

    user_movie_matrix = create_user_movie_matrix(clean_watch_history_df)

    recommender = MovieRecommender(
        movies_df=movies_df,
        watch_history_df=clean_watch_history_df,
        user_movie_matrix=user_movie_matrix
    )

    return (
        movies_df,
        users_df,
        raw_watch_history_df,
        clean_watch_history_df,
        user_movie_matrix,
        recommender
    )


(
    movies_df,
    users_df,
    raw_watch_history_df,
    clean_watch_history_df,
    user_movie_matrix,
    recommender
) = load_data()


# ============================================================
# 5. HELPER FUNCTIONS
# ============================================================

def create_bar_chart(data, title, xlabel, ylabel, rotation=45):
    """
    Cette fonction cree un graphique en barres Matplotlib.
    """

    fig, ax = plt.subplots(figsize=(10, 5))

    ax.bar(data.index, data.values)

    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)

    plt.xticks(rotation=rotation, ha="right")
    plt.tight_layout()

    return fig


def filter_watch_history(df, selected_genre, selected_min_rating):
    """
    Cette fonction applique les filtres selectionnes par l'admin.
    """

    filtered_df = df.copy()

    if selected_genre != "All":
        filtered_df = filtered_df[filtered_df["genre"] == selected_genre]

    filtered_df = filtered_df[filtered_df["rating"] >= selected_min_rating]

    return filtered_df


def show_kpi_cards(df, movies_df, users_df):
    """
    Cette fonction affiche les cartes KPI principales.
    """

    total_movies = movies_df.shape[0]
    total_users = users_df.shape[0]
    total_views = df.shape[0]

    if df.empty:
        average_rating = 0
        dominant_genre = "N/A"
        most_active_user = "N/A"
    else:
        average_rating = round(df["rating"].mean(), 2)
        dominant_genre = df["genre"].value_counts().idxmax()
        most_active_user = df["user_name"].value_counts().idxmax()

    col1, col2, col3, col4, col5, col6 = st.columns(6)

    col1.metric("Films", total_movies)
    col2.metric("Utilisateurs", total_users)
    col3.metric("Visionnages", total_views)
    col4.metric("Note moyenne", average_rating)
    col5.metric("Genre dominant", dominant_genre)
    col6.metric("Top utilisateur", most_active_user)


def plotly_bar_chart(df, x, y, title):
    """
    Cette fonction cree un graphique en barres interactif avec Plotly.
    """

    fig = px.bar(
        df,
        x=x,
        y=y,
        title=title,
        template="plotly_dark"
    )

    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(17,24,39,0.8)",
        font=dict(color="white"),
        title_font=dict(size=22, color="white")
    )

    return fig


# ============================================================
# 6. SIDEBAR
# ============================================================

st.sidebar.title("🎬 CineMatch AI")
st.sidebar.write("Admin Dashboard")

page = st.sidebar.radio(
    "Navigation",
    [
        "Accueil",
        "Vue globale",
        "Live Monitoring",
        "Donnees brutes",
        "Donnees nettoyees",
        "Comparaison avant / apres",
        "Qualite des donnees",
        "Analyse des genres",
        "Analyse utilisateurs",
        "Recommandation",
        "Rapport final"
    ]
)

st.sidebar.markdown("---")

st.sidebar.subheader("Filtres admin")

genres = sorted(clean_watch_history_df["genre"].dropna().unique().tolist())
genres = ["All"] + genres

selected_genre = st.sidebar.selectbox(
    "Filtrer par genre",
    genres
)

selected_min_rating = st.sidebar.slider(
    "Note minimale",
    min_value=1,
    max_value=5,
    value=1
)

filtered_clean_df = filter_watch_history(
    clean_watch_history_df,
    selected_genre,
    selected_min_rating
)

st.sidebar.markdown("---")
st.sidebar.write("Projet Hackathon 1")
st.sidebar.write("Python | Pandas | SciPy | Streamlit")


# ============================================================
# 7. HEADER PRINCIPAL
# ============================================================

st.markdown(
    """
    <div class="hero-box">
        <div class="hero-title">🎬 CineMatch AI</div>
        <div class="hero-subtitle">
            Dashboard admin pour une plateforme intelligente de recommandation de films.
            Donnees synthetiques, preprocessing, similarite utilisateurs et monitoring simule.
        </div>
    </div>
    """,
    unsafe_allow_html=True
)


# ============================================================
# 8. PAGE : ACCUEIL
# ============================================================

if page == "Accueil":

    st.header("Bienvenue dans le dashboard admin")

    st.write(
        """
        CineMatch AI simule une plateforme de streaming inspiree de Netflix.
        Le systeme genere des donnees utilisateurs, nettoie les donnees imparfaites,
        analyse les comportements et produit des recommandations personnalisees.
        """
    )

    st.subheader("Pipeline du projet")

    st.markdown(
        """
        1. Generation de donnees synthetiques avec Faker
        2. Ajout volontaire de donnees sales
        3. Nettoyage avec Pandas
        4. Analyse exploratoire
        5. Creation de la matrice utilisateur-film
        6. Calcul des similarites entre utilisateurs
        7. Generation des recommandations
        8. Visualisation dans un dashboard admin
        """
    )

    st.subheader("Vue rapide")

    show_kpi_cards(filtered_clean_df, movies_df, users_df)

    st.subheader("Apercu des donnees nettoyees")

    st.dataframe(filtered_clean_df.head(20))


# ============================================================
# 9. PAGE : VUE GLOBALE
# ============================================================

elif page == "Vue globale":

    st.header("📊 Vue globale de la plateforme")

    show_kpi_cards(filtered_clean_df, movies_df, users_df)

    st.subheader("Top 10 des films les plus regardes")

    top_movies_data = top_movies(filtered_clean_df, top_n=10)

    if top_movies_data.empty:
        st.warning("Aucune donnee disponible avec les filtres actuels.")
    else:
        top_movies_df = top_movies_data.reset_index()
        top_movies_df.columns = ["title", "views"]

        fig = plotly_bar_chart(
            top_movies_df,
            "title",
            "views",
            "Top 10 des films les plus regardes"
        )

        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Distribution des genres")

    genre_counts = genre_distribution(filtered_clean_df)

    if genre_counts.empty:
        st.warning("Aucune donnee disponible avec les filtres actuels.")
    else:
        genre_df = genre_counts.reset_index()
        genre_df.columns = ["genre", "views"]

        fig = plotly_bar_chart(
            genre_df,
            "genre",
            "views",
            "Distribution des genres regardes"
        )

        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Evolution moyenne des notes")

    rating_trend = (
        filtered_clean_df.groupby("watch_date")["rating"]
        .mean()
        .reset_index()
        .sort_values(by="watch_date")
    )

    if rating_trend.empty:
        st.warning("Aucune evolution disponible avec les filtres actuels.")
    else:
        fig = px.line(
            rating_trend,
            x="watch_date",
            y="rating",
            markers=True,
            title="Evolution des notes moyennes dans le temps",
            template="plotly_dark"
        )

        fig.update_layout(
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(17,24,39,0.8)",
            font=dict(color="white")
        )

        st.plotly_chart(fig, use_container_width=True)


# ============================================================
# 10. PAGE : LIVE MONITORING
# ============================================================

elif page == "Live Monitoring":

    st.header("📡 Live Monitoring - Simulation temps reel")

    st.write(
        """
        Cette section simule l'activite en temps reel d'une plateforme de streaming.
        Les indicateurs evoluent comme si des utilisateurs etaient actifs sur la plateforme.
        """
    )

    run_live = st.toggle("Activer la simulation temps reel", value=True)

    kpi_placeholder = st.empty()
    chart_placeholder = st.empty()
    table_placeholder = st.empty()

    if run_live:

        live_data = []

        for second in range(1, 21):

            active_users = random.randint(20, 120)
            current_views = random.randint(80, 500)
            recommendations_generated = random.randint(30, 250)
            average_rating_live = round(random.uniform(3.2, 4.9), 2)

            live_data.append({
                "time": second,
                "active_users": active_users,
                "current_views": current_views,
                "recommendations": recommendations_generated,
                "average_rating": average_rating_live
            })

            live_df = pd.DataFrame(live_data)

            with kpi_placeholder.container():

                col1, col2, col3, col4 = st.columns(4)

                col1.metric("Utilisateurs actifs", active_users)
                col2.metric("Visionnages en cours", current_views)
                col3.metric("Recommandations", recommendations_generated)
                col4.metric("Note moyenne live", average_rating_live)

            fig = go.Figure()

            fig.add_trace(go.Scatter(
                x=live_df["time"],
                y=live_df["active_users"],
                mode="lines+markers",
                name="Utilisateurs actifs"
            ))

            fig.add_trace(go.Scatter(
                x=live_df["time"],
                y=live_df["current_views"],
                mode="lines+markers",
                name="Visionnages"
            ))

            fig.add_trace(go.Scatter(
                x=live_df["time"],
                y=live_df["recommendations"],
                mode="lines+markers",
                name="Recommandations"
            ))

            fig.update_layout(
                title="Evolution simulee de l'activite en temps reel",
                xaxis_title="Temps",
                yaxis_title="Valeur",
                template="plotly_dark",
                height=500,
                paper_bgcolor="rgba(0,0,0,0)",
                plot_bgcolor="rgba(17,24,39,0.8)",
                font=dict(color="white")
            )

            chart_placeholder.plotly_chart(fig, use_container_width=True)

            latest_activity = pd.DataFrame({
                "event": [
                    "Movie watched",
                    "Recommendation generated",
                    "New rating added",
                    "User active",
                    "Genre trend updated"
                ],
                "value": [
                    random.choice(clean_watch_history_df["title"].tolist()),
                    random.choice(clean_watch_history_df["genre"].tolist()),
                    random.randint(1, 5),
                    random.choice(clean_watch_history_df["user_name"].tolist()),
                    random.choice(clean_watch_history_df["genre"].tolist())
                ],
                "status": [
                    "success",
                    "success",
                    "success",
                    "active",
                    "updated"
                ]
            })

            table_placeholder.dataframe(latest_activity)

            time.sleep(0.8)

    else:
        st.info("Active la simulation pour voir les donnees evoluer en temps reel.")


# ============================================================
# 11. PAGE : DONNEES BRUTES
# ============================================================

elif page == "Donnees brutes":

    st.header("🟥 Donnees brutes")

    st.write(
        """
        Les donnees brutes sont les donnees generees avec des erreurs volontaires :
        valeurs manquantes, doublons, notes invalides, dates manquantes
        et temps de visionnage incoherents.
        """
    )

    st.subheader("Apercu des donnees brutes")
    st.dataframe(raw_watch_history_df.head(100))

    st.subheader("Dimensions")
    st.write(raw_watch_history_df.shape)

    st.subheader("Valeurs manquantes")

    missing_raw = raw_watch_history_df.isnull().sum().reset_index()
    missing_raw.columns = ["column", "missing_values"]

    st.dataframe(missing_raw)

    st.subheader("Doublons")
    st.write(raw_watch_history_df.duplicated().sum())

    st.subheader("Statistiques descriptives")
    st.dataframe(raw_watch_history_df.describe())


# ============================================================
# 12. PAGE : DONNEES NETTOYEES
# ============================================================

elif page == "Donnees nettoyees":

    st.header("🟩 Donnees nettoyees")

    st.write(
        """
        Les donnees nettoyees sont les donnees apres preprocessing :
        suppression des doublons, correction des notes invalides,
        remplacement des valeurs manquantes et traitement des temps incoherents.
        """
    )

    st.subheader("Apercu des donnees nettoyees")
    st.dataframe(filtered_clean_df.head(100))

    st.subheader("Dimensions")
    st.write(filtered_clean_df.shape)

    st.subheader("Valeurs manquantes")

    missing_clean = filtered_clean_df.isnull().sum().reset_index()
    missing_clean.columns = ["column", "missing_values"]

    st.dataframe(missing_clean)

    st.subheader("Doublons")
    st.write(filtered_clean_df.duplicated().sum())

    st.subheader("Statistiques descriptives")
    st.dataframe(filtered_clean_df.describe())


# ============================================================
# 13. PAGE : COMPARAISON AVANT / APRES
# ============================================================

elif page == "Comparaison avant / apres":

    st.header("🔁 Comparaison avant / apres nettoyage")

    comparison = compare_before_after_cleaning(
        raw_watch_history_df,
        clean_watch_history_df
    )

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Lignes brutes", comparison["raw_rows"])
    col2.metric("Lignes nettoyees", comparison["clean_rows"])
    col3.metric("Valeurs manquantes brutes", comparison["raw_missing_values"])
    col4.metric("Valeurs manquantes nettoyees", comparison["clean_missing_values"])

    st.subheader("Tableau comparatif")

    comparison_df = pd.DataFrame(
        list(comparison.items()),
        columns=["metric", "value"]
    )

    st.dataframe(comparison_df)

    st.subheader("Valeurs manquantes avant / apres nettoyage")

    raw_missing = raw_watch_history_df.isnull().sum()
    clean_missing = clean_watch_history_df.isnull().sum()

    missing_comparison_df = pd.DataFrame({
        "column": raw_missing.index,
        "raw_missing": raw_missing.values,
        "clean_missing": clean_missing.values
    })

    st.dataframe(missing_comparison_df)

    fig = go.Figure()

    fig.add_trace(go.Bar(
        x=missing_comparison_df["column"],
        y=missing_comparison_df["raw_missing"],
        name="Raw missing"
    ))

    fig.add_trace(go.Bar(
        x=missing_comparison_df["column"],
        y=missing_comparison_df["clean_missing"],
        name="Clean missing"
    ))

    fig.update_layout(
        title="Valeurs manquantes avant / apres nettoyage",
        xaxis_title="Colonnes",
        yaxis_title="Nombre de valeurs manquantes",
        barmode="group",
        template="plotly_dark",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(17,24,39,0.8)",
        font=dict(color="white")
    )

    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Doublons avant / apres")

    duplicates_df = pd.DataFrame({
        "dataset": ["Raw data", "Clean data"],
        "duplicates": [
            comparison["raw_duplicates"],
            comparison["clean_duplicates"]
        ]
    })

    fig = plotly_bar_chart(
        duplicates_df,
        "dataset",
        "duplicates",
        "Doublons avant / apres nettoyage"
    )

    st.plotly_chart(fig, use_container_width=True)


# ============================================================
# 14. PAGE : QUALITE DES DONNEES
# ============================================================

elif page == "Qualite des donnees":

    st.header("🧹 Qualite des donnees")

    st.write(
        """
        Cette section permet de verifier la qualite des donnees avant et apres nettoyage.
        """
    )

    dataset_choice = st.radio(
        "Choisir le dataset",
        ["Donnees brutes", "Donnees nettoyees"]
    )

    if dataset_choice == "Donnees brutes":
        selected_df = raw_watch_history_df
    else:
        selected_df = clean_watch_history_df

    st.subheader("Apercu du dataset selectionne")
    st.dataframe(selected_df.head(50))

    st.subheader("Resume de la qualite")

    quality_df = data_quality_summary(selected_df)
    st.dataframe(quality_df)

    st.subheader("Graphique des valeurs manquantes")

    fig = plotly_bar_chart(
        quality_df,
        "column",
        "missing_values",
        "Valeurs manquantes par colonne"
    )

    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Verification des valeurs invalides")

    invalid_rating_count = selected_df[
        (selected_df["rating"] < 1) | (selected_df["rating"] > 5)
    ].shape[0]

    invalid_watch_time_count = selected_df[
        (selected_df["watch_time"] <= 0) | (selected_df["watch_time"] > 240)
    ].shape[0]

    col1, col2 = st.columns(2)

    col1.metric("Notes invalides", invalid_rating_count)
    col2.metric("Temps invalides", invalid_watch_time_count)


# ============================================================
# 15. PAGE : ANALYSE DES GENRES
# ============================================================

elif page == "Analyse des genres":

    st.header("🎭 Analyse des genres")

    st.write("Les analyses sont effectuees sur les donnees nettoyees filtrees.")

    st.subheader("Nombre de visionnages par genre")

    genre_counts = genre_distribution(filtered_clean_df)

    if genre_counts.empty:
        st.warning("Aucune donnee disponible avec les filtres actuels.")
    else:
        genre_df = genre_counts.reset_index()
        genre_df.columns = ["genre", "views"]

        fig = plotly_bar_chart(
            genre_df,
            "genre",
            "views",
            "Nombre de visionnages par genre"
        )

        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Note moyenne par genre")

    avg_rating = average_rating_by_genre(filtered_clean_df)

    if avg_rating.empty:
        st.warning("Aucune donnee disponible avec les filtres actuels.")
    else:
        avg_rating_df = avg_rating.reset_index()
        avg_rating_df.columns = ["genre", "average_rating"]

        fig = plotly_bar_chart(
            avg_rating_df,
            "genre",
            "average_rating",
            "Note moyenne par genre"
        )

        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Temps moyen de visionnage par genre")

    avg_watch_time = average_watch_time_by_genre(filtered_clean_df)

    if avg_watch_time.empty:
        st.warning("Aucune donnee disponible avec les filtres actuels.")
    else:
        avg_watch_time_df = avg_watch_time.reset_index()
        avg_watch_time_df.columns = ["genre", "average_watch_time"]

        fig = plotly_bar_chart(
            avg_watch_time_df,
            "genre",
            "average_watch_time",
            "Temps moyen de visionnage par genre"
        )

        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Test Chi-square sur les genres")

    if filtered_clean_df.empty:
        st.warning("Test impossible : aucune donnee apres filtrage.")
    else:
        chi_stat, p_value = chi_square_genre_test(filtered_clean_df)

        st.write("Chi-square statistic :", chi_stat)
        st.write("P-value :", p_value)

        if p_value < 0.05:
            st.warning("Les genres ne sont pas regardes de facon equilibree.")
        else:
            st.success("Les genres sont regardes de facon assez equilibree.")


# ============================================================
# 16. PAGE : ANALYSE UTILISATEURS
# ============================================================

elif page == "Analyse utilisateurs":

    st.header("👥 Analyse des utilisateurs")

    st.write("Les analyses sont effectuees sur les donnees nettoyees filtrees.")

    st.subheader("Utilisateurs les plus actifs")

    active_users = most_active_users(filtered_clean_df, top_n=10)

    if active_users.empty:
        st.warning("Aucune donnee disponible avec les filtres actuels.")
    else:
        active_users_df = active_users.reset_index()
        active_users_df.columns = ["user_name", "views"]

        fig = plotly_bar_chart(
            active_users_df,
            "user_name",
            "views",
            "Top utilisateurs les plus actifs"
        )

        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Heatmap utilisateurs / genres")

    if filtered_clean_df.empty:
        st.warning("Aucune donnee disponible avec les filtres actuels.")
    else:
        heatmap_data = pd.crosstab(
            filtered_clean_df["user_name"],
            filtered_clean_df["genre"]
        )

        fig = px.imshow(
            heatmap_data,
            text_auto=True,
            aspect="auto",
            title="Heatmap utilisateurs / genres",
            template="plotly_dark"
        )

        fig.update_layout(
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(17,24,39,0.8)",
            font=dict(color="white")
        )

        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Evolution des notes moyennes dans le temps")

    rating_trend = (
        filtered_clean_df.groupby("watch_date")["rating"]
        .mean()
        .reset_index()
        .sort_values(by="watch_date")
    )

    if rating_trend.empty:
        st.warning("Aucune donnee disponible avec les filtres actuels.")
    else:
        fig = px.line(
            rating_trend,
            x="watch_date",
            y="rating",
            markers=True,
            title="Evolution des notes moyennes",
            template="plotly_dark"
        )

        fig.update_layout(
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(17,24,39,0.8)",
            font=dict(color="white")
        )

        st.plotly_chart(fig, use_container_width=True)


# ============================================================
# 17. PAGE : RECOMMANDATION
# ============================================================

elif page == "Recommandation":

    st.header("🤖 Moteur de recommandation")

    st.write(
        """
        Les recommandations sont basees sur les donnees nettoyees.
        Le systeme utilise les genres favoris, les films deja regardes,
        la popularite des films et les utilisateurs similaires.
        """
    )

    user_list = users_df["name"].tolist()

    selected_user = st.selectbox(
        "Choisir un utilisateur",
        user_list
    )

    st.subheader("Informations utilisateur")

    selected_user_info = users_df[users_df["name"] == selected_user]
    st.dataframe(selected_user_info)

    st.subheader("Films deja regardes")

    watched_movies = recommender.get_user_watched_movies(selected_user)

    if len(watched_movies) == 0:
        st.info("Cet utilisateur n'a pas encore regarde de films.")
    else:
        st.write(watched_movies)

    st.subheader("Genres favoris")

    favorite_genres = recommender.get_user_favorite_genres(selected_user)
    st.write(favorite_genres)

    st.subheader("Utilisateurs similaires")

    similar_users = recommender.find_similar_users(selected_user, top_n=3)
    st.dataframe(similar_users)

    st.subheader("Recommandations finales")

    recommendations = recommender.hybrid_recommendation(selected_user, top_n=5)

    if recommendations.empty:
        st.warning("Aucune recommandation disponible pour cet utilisateur.")
    else:
        st.dataframe(recommendations)

        fig = plotly_bar_chart(
            recommendations,
            "title",
            "score",
            "Score des films recommandes"
        )

        st.plotly_chart(fig, use_container_width=True)


# ============================================================
# 18. PAGE : RAPPORT FINAL
# ============================================================

elif page == "Rapport final":

    st.header("📄 Rapport final du projet")

    st.subheader("Presentation")

    st.write(
        """
        CineMatch AI est un systeme de recommandation de films inspire des plateformes
        de streaming comme Netflix. Le projet montre comment les donnees utilisateurs
        peuvent etre generees, nettoyees, analysees et utilisees pour produire des
        recommandations personnalisees.
        """
    )

    st.subheader("Architecture")

    st.code(
        """
cinematch_ai/
│
├── data_generator.py
├── preprocessing.py
├── recommender.py
├── analytics.py
├── dashboard.py
├── main.py
└── web_admin.py
        """,
        language="text"
    )

    st.subheader("Technologies utilisees")

    st.markdown(
        """
        - **Python** : langage principal du projet
        - **Faker** : generation de donnees synthetiques
        - **NumPy** : generation de valeurs aleatoires
        - **Pandas** : nettoyage, transformation et analyse des donnees
        - **SciPy** : tests statistiques et similarite
        - **Matplotlib / Seaborn** : visualisations classiques
        - **Plotly** : graphiques interactifs modernes
        - **Streamlit** : dashboard web admin
        """
    )

    st.subheader("Preprocessing")

    st.write(
        """
        Pour rendre le projet realiste, nous avons volontairement introduit
        des problemes de qualite dans les donnees : valeurs manquantes,
        doublons, notes invalides, temps incoherents et dates manquantes.

        Ensuite, nous avons nettoye les donnees avec Pandas.
        """
    )

    st.subheader("Moteur de recommandation")

    st.write(
        """
        Le moteur de recommandation utilise une approche hybride :
        - recommandation par genres favoris ;
        - recommandation par utilisateurs similaires ;
        - exclusion des films deja regardes ;
        - classement par score.
        """
    )

    st.subheader("Dashboard admin")

    st.write(
        """
        Le dashboard permet de visualiser les donnees brutes, les donnees nettoyees,
        la comparaison avant/apres nettoyage, les analyses utilisateurs,
        les analyses des genres, les recommandations et une simulation temps reel.
        """
    )

    st.subheader("Conclusion")

    st.success(
        """
        CineMatch AI montre comment une plateforme de streaming peut utiliser
        les donnees utilisateurs pour nettoyer, analyser et recommander des films
        personnalises a chaque utilisateur.
        """
    )